version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - make build
      - aws cloudformation package --template-file ./stacks/infrastructure.yml --s3-bucket core-infrastructure-eu-w-buildartifactsbucketeuwe-12d2acmozch84 --s3-prefix artifacts/traffic-tracker --output-template-file ./stacks/infrastructure.yml
