version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - apt-get update -y && apt-get install jq -y
      - cd website
      - npm ci
      - npm t
      - sh package.sh
artifacts:
  files:
    - "**/*"
