version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd website
      - npm ci
      - npm t
      - npm run build:prod
      - aws s3 cp build s3://$BUCKET --cache-control max-age=60 --acl public-read --recursive
artifacts:
  files:
    - "**/*"
