version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd website
      - npm ci
      - npm t
      - npm run build:prod
      - aws sts assume-role --role-arn arn:aws:iam::008356366354:role/projects-live-bucket-BucketUploadRole-1USRJUF87S00F --role-session-name "$PROJECT_NAME-$CODEBUILD_BUILD_NUMBER"
      - aws s3 sync build s3://projects-live-bucket-bucket-llkgmktc4xmo/traffic-tracker --cache-control max-age=60 --acl public-read --delete
artifacts:
  files:
    - "**/*"
